OvmsClient:
  PipelineScript: run_grpc_kserv.sh
  PipelineInputArgs: "--model_name instance_segmentation_omz_1040" # space delimited like we run the script in command and take those input arguments
  # PipelineInputArgs: "--model_name bit_64" # space delimited like we run the script in command and take those input arguments
  # PipelineInputArgs: "--model_name yolov5s" # space delimited like we run the script in command and take those input arguments