OvmsClient:
  PipelineScript: run_classification.sh
  PipelineInputArgs: "" # space delimited like we run the script in command and take those input arguments
  EnvironmentVariableFiles:
    - classification.env